@startuml vcRiquinho

title Diagrama de Classes - VcRiquinho
Alice -> Bob : hello

class Cliente {
    +String nome
    +int idade
    +double saldo
    +String tipoConta
    
    +void atualizarSaldo(double valor)

    +void depositar(double valor)
    +void sacar(double valor)
}

@enduml
